image: gitlab.kwant-project.org:5005/qt/research-docker

run profiler:
  script:
    - cd codes; export PYTHONPATH="."; cd ..
    - pip install memray pyinstrument
    - python profiling/graphene.py
  artifacts:
    paths:
      - timeProfile.html
      - memoryProfile.bin

run tests:
  # Needed because of coverage reports
  script:
    - pip install pytest-cov pytest-randomly pytest-repeat pytest-ruff pytest-regressions
    - py.test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
