image: gitlab.kwant-project.org:5005/qt/research-docker

stages:
  - run profiler
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - shopt -s nullglob  # sane behaviour when globs do not match
  - pip install gitlab-ci-tools  # for last-good-build
  - LAST_GOOD_SHA=$(last-good-build || echo '')

run profiler:
  script:
    - pip install memray pyinstrument
    - python profiling/graphene.py
  stage: run profiler