image: gitlab.kwant-project.org:5005/qt/research-docker

stages:
  - run analysis
  - build documents

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - shopt -s nullglob  # sane behaviour when globs do not match
  - pip install gitlab-ci-tools  # for last-good-build
  - LAST_GOOD_SHA=$(last-good-build || echo '')

run analysis:
  script:
    - cd analysis
    - for ipynb in *.ipynb; do
    -   jupyter nbconvert --to notebook --execute $ipynb
    - done
  artifacts:
    paths:
      - analysis/*.ipynb
    expire_in: 1 month
  stage: run analysis


.pdf-build:
  stage: build documents
  script:
    - cd $CWD
    - if [ -d images ]; then
    -   cd images
    -   for image in *.svg; do
    -     inkscape -o "${image%.*}.pdf" $image
    -   done
    -   cd ..
    -  fi
    - for tex in *.tex; do
    -   if grep "documentclass" $tex >/dev/null; then
    -     latexmk -pdf $tex
    -     DIFF="$(git diff $LAST_GOOD_SHA -- $tex || echo '')"
    -     OLD_EXISTS="$(git ls-tree --name-only $LAST_GOOD_SHA | grep -x $tex || echo '')"
    -     if [ "$LAST_GOOD_SHA" ] && [ "$DIFF" ] && [ "$OLD_EXISTS" ]; then
    -       git show $LAST_GOOD_SHA:$CWD/$tex > old_$tex
    -       latexdiff old_$tex $tex > diff_$tex || true
    -       rm old_$tex
    -       latexmk -pdf diff_$tex || true
    -     fi
    -   fi
    - done

build notes:
  extends: .pdf-build
  variables:
    CWD: notes
  artifacts:
    paths:
      - notes/*.pdf
    expire_in: 1 month

build publication:
  extends: .pdf-build
  variables:
    CWD: publication
  after_script:
    - mkdir -p public && cp -r $CWD/*.pdf public
  artifacts:
    paths:
      - publication/*.pdf
    expire_in: 1 month
  stage: build documents
