repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^third_party/eigen/
    -   id: end-of-file-fixer
        exclude: ^third_party/eigen/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
    -   id: ruff
        args: [--fix]
        exclude: ^third_party/eigen/
    -   id: ruff-format
        exclude: ^third_party/eigen/
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        exclude: ^third_party/eigen/
        additional_dependencies:
        - tomli
