
[project]
name = "scattering-hotis"
version = "0.1.0"
description = "Add a short description here"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
matplotlib-base = ">=3.8.4,<3.9"
scipy = ">=1.14.0,<1.15"
numpy = "*"
ipython = ">=8.22.2,<8.23"
ipykernel = ">=6.29.4,<6.30"
pfapack = ">=0.1.1,<0.2"
adaptive = ">=1.3.0,<1.4"
git = ">=2.33.0"  # To install networkmodels
python-mumps = ">=0.0.2,<0.0.3"
jupytext = ">=1.16.4,<1.17"
cmasher = ">=1.8.0,<2"
svgutils = ">=0.3.4,<0.4"
pybtex = ">=0.24.0,<0.25"
tectonic = "*"
tomlkit = ">=0.13.2,<0.14"
myst-nb = ">=1.1.2,<2"
pytest-cov = ">=6.0.0,<7"
pytest-randomly = ">=3.15.0,<4"
pytest-repeat = ">=0.9.3,<0.10"
pytest = ">=8.3.4,<9"
sparse = ">=0.15"

[target.linux-64.dependencies]
kwant = ">=1.5.0"
pre-commit = ">=3.7.1,<3.8"

[target.osx-64.dependencies]
kwant = ">=1.5.0"

[target.win-64.dependencies]
kwant = ">=1.5.0"
pre-commit = ">=3.7.1,<3.8"

[target.osx-arm64.dependencies]
pre-commit = ">=3.7.1,<3.8"

[pypi-dependencies]
skunk = { git = "https://github.com/akhmerov/skunk.git" }
pytest-ruff = ">=0.4.1,<0.5"

[target.linux-64.pypi-dependencies]
meanfi = { path = ".", editable = true }

[target.osx-64.pypi-dependencies]
meanfi = { path = ".", editable = true }

[target.win-64.pypi-dependencies]
meanfi = { path = ".", editable = true }

[feature.empty.dependencies]

[environments]
default = { solve-group = "default" }
empty = { features = ["empty"], no-default-feature = true }
zip = { features = ["zip"], no-default-feature = true }

[feature.zip.target.linux-64.dependencies]
zip = "*"

[feature.zip.target.osx-64.dependencies]
zip = ">=3.0,<4"

[feature.empty.system-requirements]
libc = { family = "unix", version = "0" }
