[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "meanfi"
dynamic = ["version"]
authors = [
  {name="MeanFi developers"},
]
description = "Package to perform self-consistent mean-field calculations on tight-binding systems"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[tool.hatch.version]
source = "vcs"
[tool.hatch.build.hooks.vcs]
version-file = "meanfi/_version.py"

[project.urls]
"Documentation" = "https://meanfi.readthedocs.io/en/latest/"
"Repository" = "https://gitlab.kwant-project.org/qt/meanfi"
"Bug Tracker" = "https://gitlab.kwant-project.org/qt/meanfi/-/issues"

[tool.hatch.build.targets.wheel]
packages = ["meanfi"]

[tool.hatch.build.targets.sdist]
include = [
  "meanfi",
  "README.md",
  "LICENSE",
  "pyproject.toml",
  "AUTHORS.md",
]

[tool.codespell]
skip = "*.ipynb"
ignore-words-list = "multline, ket, bra, braket, nwo, mater"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
meanfi = { path = ".", editable = true }


[tool.pixi.dependencies]
python = ">=3.12.8,<4"
numpy = ">=2.2.2,<3"
kwant = ">=1.5.0,<2"
matplotlib = ">=3.10.0,<4"
scipy = "==1.15.1"
ipykernel = ">=6.29.5,<7"
